const config = require('./config.json');
module.exports = function dropnotice(dispatch) {
const command = dispatch.command
let enabled = config.toggle;

command.add('dropnotice', () => {
enabled = !enabled
command.message(`Drop-Notice is now ${enabled ? 'enabled' : 'disabled'}.`)})

dispatch.hook('S_SPAWN_DROPITEM', 8, (event) => {
if(!enabled) return;
else if(event.item === 366)
command.message('<font color="#08ad05" size="30">Рубин')
else if(event.item === 367)
command.message('<font color="#2478FF" size="30">Сапфир')
else if(event.item === 368)
command.message('<font color="#2478FF" size="30">Изумруд')
if(event.item === 369)
command.message('<font color="#E69F00" size="30">Бриллиант')
if(event.item === 28620)
command.message('<font color="#E69F00" size="30">Чертежи природных камней: Гармония дисбаланса')
else if(event.item === 98281)
command.message('<font color="#E69F00" size="30">Ящик с легендарными гравировками')
else if(event.item === 98532)
command.message('<font color="#E69F00" size="30">Ящик со снаряжением ревущей ярости')
else if(event.item === 98531)
command.message('<font color="#E69F00" size="30">Ящик со снаряжением из ледяной стали')

else if(event.item === 28607)
command.message('<font color="#E69F00" size="30">Чертежи драгоценных камней: Бриллиант')
else if(event.item === 28601)
command.message('<font color="#E69F00" size="30">Чертежи материалов зачарования: Золотая пластина TERA')
else if(event.item === 28603)
command.message('<font color="#E69F00" size="30">Чертежи материалов зачарования: Серебряная пластина TERA')
else if(event.item === 6961)
command.message('<font color="##E69F00" size="30">Гравировка броши: Пульсация II')
else if(event.item === 6962)
command.message('<font color="##E69F00" size="30">Гравировка броши: Острота II')
else if(event.item === 6963)
command.message('<font color="##E69F00" size="30">Гравировка броши: Поступь хищника II')
else if(event.item === 88637)
command.message('<font color="#E69F00" size="30">Маска безграничности')
else if(event.item === 88636)
command.message('<font color="#E69F00" size="30">Маска безграничности')
else if(event.item === 88638)
command.message('<font color="#E69F00" size="30">Маска безграничности')
else if(event.item === 88635)
command.message('<font color="#E69F00" size="30">Маска безграничности')
else if(event.item === 88634)
command.message('<font color="#E69F00" size="30">Маска истоков')
else if(event.item === 88632)
command.message('<font color="#E69F00" size="30">Маска истоков')
else if(event.item === 88633)
command.message('<font color="#E69F00" size="30">Маска истоков')
else if(event.item === 88631)
command.message('<font color="#E69F00" size="30">Маска истоков')
else if(event.item === 88787)
command.message('<font color="#E69F00" size="30">Маска крови Эллеона')
else if(event.item === 88786)
command.message('<font color="#E69F00" size="30">Маска крови Эллеона')
else if(event.item === 88785)
command.message('<font color="#E69F00" size="30">Маска крови Эллеона')
else if(event.item === 88784)
command.message('<font color="#E69F00" size="30">Маска крови Эллеона')
else if(event.item === 88849)
command.message('<font color="#E69F00" size="30">Маска Бахаара')
else if(event.item === 88850)
command.message('<font color="#E69F00" size="30">Маска Бахаара')
else if(event.item === 88851)
command.message('<font color="#E69F00" size="30">Маска Бахаара')
else if(event.item === 88852)
command.message('<font color="#E69F00" size="30">Маска Бахаара')
else if(event.item === 88827)
command.message('<font color="#E69F00" size="30">Усилитель для пояса I')
else if(event.item === 88828)
command.message('<font color="#E69F00" size="30">Усилитель для амулета I')
else if(event.item === 88829)
command.message('<font color="#E69F00" size="30">Усилитель для серег I')
else if(event.item === 88830)
command.message('<font color="#E69F00" size="30">Усилитель для кольца I')
else if(event.item === 88831)
command.message('<font color="#E69F00" size="30">Усилитель для венца I')
else if(event.item === 88836)
command.message('<font color="#E69F00" size="30">Усилитель для венца II')
else if(event.item === 88835)
command.message('<font color="#E69F00" size="30">Усилитель для кольца II')
else if(event.item === 88834)
command.message('<font color="#E69F00" size="30">Усилитель для серег II')
else if(event.item === 88833)
command.message('<font color="#E69F00" size="30">Усилитель для амулета II')
else if(event.item === 88832)
command.message('<font color="#E69F00" size="30">Усилитель для пояса II')

else if(event.item === 204257)
command.message('<font color="#E69F00" size="30">Усилитель для пояса I')
else if(event.item === 204258)
command.message('<font color="#E69F00" size="30">Усилитель для амулета I')
else if(event.item === 204259)
command.message('<font color="#E69F00" size="30">Усилитель для серег I')
else if(event.item === 204260)
command.message('<font color="#E69F00" size="30">Усилитель для кольца I')
else if(event.item === 204261)
command.message('<font color="#E69F00" size="30">Усилитель для венца I')
else if(event.item === 204266)
command.message('<font color="#E69F00" size="30">Усилитель для венца II')
else if(event.item === 204265)
command.message('<font color="#E69F00" size="30">Усилитель для кольца II')
else if(event.item === 204264)
command.message('<font color="#E69F00" size="30">Усилитель для серег II')
else if(event.item === 204263)
command.message('<font color="#E69F00" size="30">Усилитель для амулета II')
else if(event.item === 204262)
command.message('<font color="#E69F00" size="30">Усилитель для пояса II')

else if(event.item === 6780)
command.message('<font color="#E69F00" size="30">Гравировка серег: Пульсация III')
else if(event.item === 6781)
command.message('<font color="#E69F00" size="30">Гравировка серег: Острота III')
else if(event.item === 6782)
command.message('<font color="#E69F00" size="30">Гравировка серег: Поступь хищника III')
else if(event.item === 6785)
command.message('<font color="##E69F00" size="30">Усиленная гравировка серег: Пульсация III')
else if(event.item === 6786)
command.message('<font color="##E69F00" size="30">Усиленная гравировка серег: Острота III')
else if(event.item === 6787)
command.message('<font color="##E69F00" size="30">Усиленная гравировка серег: Поступь хищника III')
else if(event.item === 6941)
command.message('<font color="#E69F00" size="30">Гравировка пояса: Острота III')
else if(event.item === 6946)
command.message('<font color="##E69F00" size="30">Усиленная гравировка пояса: Острота III')
else if(event.item === 6940)
command.message('<font color="#E69F00" size="30">Гравировка пояса: Пульсация III')
else if(event.item === 6945)
command.message('<font color="##E69F00" size="30">Усиленная гравировка пояса: Пульсация III')
else if(event.item === 6942)
command.message('<font color="#E69F00" size="30">Гравировка пояса: Поступь хищника III')
else if(event.item === 6947)
command.message('<font color="##E69F00" size="30">Усиленная гравировка пояса: Поступь хищника III')
else if(event.item === 6701)
command.message('<font color="#E69F00" size="30">Гравировка амулетов: Острота III')
else if(event.item === 6706)
command.message('<font color="##E69F00" size="30">Усиленная гравировка амулетов: Острота III')
else if(event.item === 6700)
command.message('<font color="#E69F00" size="30">Гравировка амулетов: Пульсация III')
else if(event.item === 6705)
command.message('<font color="##E69F00" size="30">Усиленная гравировка амулетов: Пульсация III')
else if(event.item === 6702)
command.message('<font color="#E69F00" size="30">Гравировка амулетов: Поступь хищника III')
else if(event.item === 6707)
command.message('<font color="##E69F00" size="30">Усиленная гравировка амулетов: Поступь хищника III')
else if(event.item === 6862)
command.message('<font color="#E69F00" size="30">Гравировка кольца: Поступь хищника III')
else if(event.item === 6867)
command.message('<font color="##E69F00" size="30">Усиленная гравировка кольца: Поступь хищника III')
else if(event.item === 6861)
command.message('<font color="#E69F00" size="30">Гравировка кольца: Острота III')
else if(event.item === 6866)
command.message('<font color="##E69F00" size="30">Усиленная гравировка кольца: Острота III')
else if(event.item === 6860)
command.message('<font color="#E69F00" size="30">Гравировка кольца: Пульсация III')
else if(event.item === 6865)
command.message('<font color="##E69F00" size="30">Усиленная гравировка кольца: Пульсация III')
else if(event.item === 6958)
command.message('<font color="#E69F00" size="30">Гравировка броши: Пульсация I')
else if(event.item === 6959)
command.message('<font color="#E69F00" size="30">Гравировка броши: Острота I')
else if(event.item === 6960)
command.message('<font color="#E69F00" size="30">Гравировка броши: Поступь хищника I')
else if(event.item === 28600)
command.message('<font color="#E69F00" size="30">Чертежи материалов зачарования: Золотой осколок TERA')
else if(event.item === 28602)
command.message('<font color="#E69F00" size="30">Чертежи материалов зачарования: Серебряный осколок TERA')

else if(event.item === 98598)
command.message('<font color="#E69F00" size="30">Старые припасы')
else if(event.item === 98599)
command.message('<font color="#E69F00" size="30">Коготь черта')
else if(event.item === 98600)
command.message('<font color="#E69F00" size="30">Череп дракона')

else if(event.item === 98698)
command.message('<font color="#E69F00" size="30">Парные клинки Аслана')
else if(event.item === 98699)
command.message('<font color="#E69F00" size="30">Копье Аслана')
else if(event.item === 98700)
command.message('<font color="#E69F00" size="30">Двуручный меч Аслана')
else if(event.item === 98701)
command.message('<font color="#E69F00" size="30">Топор Аслана')
else if(event.item === 98702)
command.message('<font color="#E69F00" size="30">Диск Аслана')
else if(event.item === 98703)
command.message('<font color="#E69F00" size="30">Лук Аслана')
else if(event.item === 98704)
command.message('<font color="#E69F00" size="30">Посох Аслана')
else if(event.item === 98705)
command.message('<font color="#E69F00" size="30">Жезл Аслана')
else if(event.item === 98706)
command.message('<font color="#E69F00" size="30">Коса Аслана')
else if(event.item === 98707)
command.message('<font color="#E69F00" size="30">Мегапушка Аслана')
else if(event.item === 98708)
command.message('<font color="#E69F00" size="30">Силовые кулаки Аслана')
else if(event.item === 98709)
command.message('<font color="#E69F00" size="30">Сюрикен Аслана')
else if(event.item === 98710)
command.message('<font color="#E69F00" size="30">Глефа Аслана')
else if(event.item === 98711)
command.message('<font color="#E69F00" size="30">(Умный) ящик: Оружие Аслана')


else if(event.item === 98712)
command.message('<font color="#E69F00" size="30">(Умный) ящик: Рецепт оружия Аслана')
else if(event.item === 98713)
command.message('<font color="#2478FF" size="30">Секрет получения острого темного осколка')
else if(event.item === 98714)
command.message('<font color="#2478FF" size="30">Секрет получения прочного темного осколка')


else if(event.item === 88982)
command.message('<font color="#E69F00" size="30">Сундук с ржавым геройским оружием')
else if(event.item === 88985)
command.message('<font color="#E69F00" size="30">Сундук с ржавыми геройскими доспехами')
else if(event.item === 88988)
command.message('<font color="#E69F00" size="30">Сундук с ржавыми геройскими перчатками')
else if(event.item === 88991)
command.message('<font color="#E69F00" size="30">Сундук с ржавыми геройскими сапогами')



else if(event.item === 206970)
command.message('<font color="#E69F00" size="30">Легендарное оружие Эксодора')
else if(event.item === 206971)
command.message('<font color="#E69F00" size="30">Легендарная броня Эксодора')
else if(event.item === 206972)
command.message('<font color="#E69F00" size="30">Легендарное оружие Эксодора (класс)')
else if(event.item === 206973)
command.message('<font color="#E69F00" size="30">Легендарная броня Эксодора (класс)')


else if(event.item === 206950)
command.message('<font color="#E69F00" size="30">Сундук с легендарным оружием Эксодора')
else if(event.item === 206951)
command.message('<font color="#E69F00" size="30">Сундук с легендарной броней Эксодора')
else if(event.item === 206952)
command.message('<font color="#E69F00" size="30">Сундук с легендарными перчатками Эксодора')
else if(event.item === 206953)
command.message('<font color="#E69F00" size="30">Сундук с легендарными сапогами Эксодора')
else if(event.item === 209125)
command.message('<font color="#E69F00" size="30">Сундук с легендарным поясом Эксодора')
else if(event.item === 209126)
command.message('<font color="#E69F00" size="30">Сундук с легендарной маской Эксодора')


else if(event.item === 888875)
command.message('<font color="#E69F00" size="30">Брошь уничтожения')
else if(event.item === 88876)
command.message('<font color="#E69F00" size="30">Брошь уничтожения')
else if(event.item === 88877)
command.message('<font color="#E69F00" size="30">Брошь уничтожения')
else if(event.item === 88878)
command.message('<font color="#E69F00" size="30">Брошь уничтожения')


else if(event.item === 88879)
command.message('<font color="#E69F00" size="30">Брошь черного солнца')
else if(event.item === 88880)
command.message('<font color="#E69F00" size="30">Брошь черного солнца')
else if(event.item === 88881)
command.message('<font color="#E69F00" size="30">Брошь черного солнца')
else if(event.item === 88882)
command.message('<font color="#E69F00" size="30">Брошь черного солнца')

else if(event.item === 98677)
command.message('<font color="#E69F00" size="30">Сырье для волшебного оружия из темного осколка')
else if(event.item === 98678)
command.message('<font color="#E69F00" size="30">Сырье для волшебной брони из темного осколка')

else if(event.item === 90923)
command.message('<font color="#e600a2" size="30">Сундук со снаряжением Кайи')
else if(event.item === 98778)
command.message('<font color="#2478FF" size="30">Черный кристалл')
else if(event.item === 98779)
command.message('<font color="#E69F00" size="30">Темный кристалл')
else if(event.item === 98780)
command.message('<font color="#98713" size="30">Шкатулка с черными кристаллами')


else if(event.item === 89141)
command.message('<font color="#E69F00" size="30">Артефакт Ишары II')
else if(event.item === 89041)
command.message('<font color="#E69F00" size="30">Реликвия Амаруна II')


else if(event.item === 98721)
command.message('<font color="#e60000" size="30">Сундук с огненным оружием Келсаика')
else if(event.item === 98722)
command.message('<font color="#e60000" size="30">Сундук с ледяным оружием Келсаика')


})
}
//
